---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ypforum/deveint.ypforum.org
    - rm -rf $DEPLOYPATH/storage/logs/*.log 2>/dev/null || true
    - /bin/rm -rf $DEPLOYPATH/vendor 2>/dev/null || true
    - /bin/cp -r app $DEPLOYPATH/
    - /bin/cp -r bootstrap $DEPLOYPATH/
    - /bin/cp -r config $DEPLOYPATH/
    - /bin/cp -r public $DEPLOYPATH/
    - /bin/cp -r resources $DEPLOYPATH/
    - /bin/cp -r routes $DEPLOYPATH/
    - /bin/cp -r vendor $DEPLOYPATH/
    - /bin/cp artisan $DEPLOYPATH/
    - /bin/cp composer.json $DEPLOYPATH/
    - /bin/cp composer.lock $DEPLOYPATH/
    - /bin/cp .env $DEPLOYPATH/
    - /bin/cp .env.example $DEPLOYPATH/
    - /bin/cp .htaccess $DEPLOYPATH/
    - /bin/cp phpunit.xml $DEPLOYPATH/ 2>/dev/null || true
    - /bin/cp .cpanel.yml $DEPLOYPATH/
    - cd $DEPLOYPATH
    - /bin/php artisan migrate --force
    - /bin/php artisan optimize:clear
    - /bin/php artisan optimize
    - /bin/php artisan config:cache
    - /bin/php artisan route:cache
    - /bin/php artisan view:cache
    - /bin/chmod -R 775 storage bootstrap/cache public
    - /bin/chmod 644 .env
